-- Note: It is strictly recommended to run 'python manage.py migrate' 
-- to set up the full Django environment (including sessions, auth, permissions).
-- The SQL below creates the tables for your custom models in Supabase (PostgreSQL).

-- 1. Create User Model (extends AbstractUser)
CREATE TABLE IF NOT EXISTS "authentication_user" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "password" varchar(128) NOT NULL,
    "last_login" timestamp with time zone NULL,
    "is_superuser" boolean NOT NULL,
    "username" varchar(150) NOT NULL UNIQUE,
    "first_name" varchar(150) NOT NULL,
    "last_name" varchar(150) NOT NULL,
    "email" varchar(254) NOT NULL,
    "is_staff" boolean NOT NULL,
    "is_active" boolean NOT NULL,
    "date_joined" timestamp with time zone NOT NULL,
    "role" varchar(20) NOT NULL,
    "phone_number" varchar(15) NULL,
    "district" varchar(100) NULL,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL
);

-- 2. Create Issue Model
CREATE TABLE IF NOT EXISTS "core_issue" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title" varchar(200) NOT NULL,
    "description" text NOT NULL,
    "category" varchar(100) NOT NULL,
    "location_lat" double precision NULL,
    "location_lng" double precision NULL,
    "address" varchar(255) NULL,
    "status" varchar(20) NOT NULL,
    "priority" varchar(20) NOT NULL,
    "image_url" varchar(500) NULL,
    "created_at" timestamp with time zone NOT NULL,
    "updated_at" timestamp with time zone NOT NULL,
    "citizen_id" bigint NOT NULL REFERENCES "authentication_user" ("id") DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX ON "core_issue" ("citizen_id");

-- 3. Create Issue Update Model
CREATE TABLE IF NOT EXISTS "core_issueupdate" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "previous_status" varchar(20) NULL,
    "new_status" varchar(20) NOT NULL,
    "comment" text NOT NULL,
    "created_at" timestamp with time zone NOT NULL,
    "admin_id" bigint NULL REFERENCES "authentication_user" ("id") DEFERRABLE INITIALLY DEFERRED,
    "issue_id" bigint NOT NULL REFERENCES "core_issue" ("id") DEFERRABLE INITIALLY DEFERRED
);
CREATE INDEX ON "core_issueupdate" ("admin_id");
CREATE INDEX ON "core_issueupdate" ("issue_id");
